name: deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    provider: pages
    strategy: git
    edge: true
    cleanup: false
    github-token: $GITHUB_TOKEN
    local-dir: book
    keep-history: false
    on:
      branch: main
    target_branch: gh-pages
    steps:
      - name: Prepare
        run: (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update) && (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.3" mdbook) && cargo install-update -a
      
      - name: Build
        run: mdbook build && mdbook test